### ISSUE TITLE
iOS OpenGLES2 is deprecated, but the readme tells me to use it

### ISSUE THREAD

**Issue by stranger-games** [f111fei/react-native-unity-view#29]
Hi,

In the readme it says:
"Other Settings find the Rendering part, uncheck the Auto Graphics API and select only OpenGLES2"

But the API is deprecated for iOS. Is there a work around? Would it work with Meta?

Regards,
Abdalla

**Comment by cybergen** [comment]
I use it with Metal, as I'm building an AR app. It seems fine for my use cases.

**Comment by f111fei** [comment]
If you use Metal, You may encounter the following problem.
https://stackoverflow.com/questions/36554891/unity-crash-on-os-x-unitygfxdeviceworker-thread-crashed

**Comment by mikeyamato** [comment]
@f111fei do you mean `OpenGLCore` as primary and `Metal` as secondary since `OpenGLES2` is not an option?

**Comment by JanOwiesniak** [comment]
I need to switch to Metal because of another 3rd party dependency i use that no longer support OpenGL.

> I use it with Metal, as I'm building an AR app. It seems fine for my use cases.

I'm using this library together with Vuforia to accomplish an AR app.
It sounds promising to me that @cybergen has a very similar use case which is working on Metal.

Until now i had set Unity Graphics APIs to:

1. OpenGLES2
2. Metal

Which works fine because the device probably used OpenGLES2 all the time.

When switching Unity Graphics APIs to (removed OpenGL from options):

1. Metal

Some things are not working anymore (i know that the README suggest to use OpenGL but this is deprecated and therefore really no long term solution).

Back to my problem:

The app still starts but Vuforia seems to have problem with the camera view video background.
I can still detect image targets but the camera background is all black now.

Does anyone experienced a similar issue before?
Maybe even solved it or has an explanation about what is going on here?
Is Vuforia not compatible with Metal? Could this be the issue?

**Comment by JanOwiesniak** [comment]
Hm there seems to be an issue with Vuforia + Metal

- https://github.com/f111fei/react-native-unity-view/issues/126
- https://developer.vuforia.com/forum/unity/vuforia-always-set-opengl-es-20
